### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by a19hu** [a19hu/SWC_2024#1]
We have to make same Navbar as given in this website [swc](http://swc.iitj.ac.in/) .
New Navbar make as given in [figma](https://www.figma.com/design/sSKEj7j6nkQKktsfHGwtzE/SWC-Web-UI?node-id=0-1&t=blhPJRpSoFZH3cA9-1) file but on hover make as website [swc](http://swc.iitj.ac.in/).

**Comment by ghost** [comment]
assign me

**Comment by gjyotin305** [comment]
@Ashutoshkumar22 Please make it responsive.

**Comment by Vishalvirdi** [comment]
Hey, Can you please assign this issue to me. I would love to contribute.

**Comment by a19hu** [comment]
@Vishalvirdi Are you working on it?

**Comment by Vishalvirdi** [comment]
Yes Almost completed.

**Comment by Vishalvirdi** [comment]
@a19hu I have created pull request please review it.

**Comment by a19hu** [comment]
> @a19hu I have created pull request please review it.

please send screenshot

**Comment by a19hu** [comment]
@Vishalvirdi one more things jab bhi pr maro please mention the issue number in the discription like #1 and then add somthing

**Comment by Vishalvirdi** [comment]
Ok , Next Time I will keep this in mind.
