### ISSUE TITLE
Counsellor Team details

### ISSUE THREAD

**Issue by a19hu** [a19hu/SWC_2024#20]
All Team details add in [swc](https://swc-taupe.vercel.app/CounsellorTeam) from [Team](http://swc.iitj.ac.in/counsellors_team.php).

![image](https://github.com/a19hu/SWC_2024/assets/132092345/cf50e7b0-628b-400a-b8d9-ce5480248742)

**Comment by sarahfatima1205** [comment]
assign this to me

**Comment by sarahfatima1205** [comment]
please merge the code
